#!/usr/bin/env python3
"""Build an allowlisted public site without reading private records or configuration."""
import argparse
import json
from pathlib import Path
import re
import shutil
import sys
import tempfile

ROOT=Path(__file__).resolve().parent.parent
sys.path.insert(0,str(ROOT))
PUBLIC_CONFIG=('roadmaps','guides','electronics_paths','ee_textbook','learning_links',
               'robotics_curriculum','agent_curriculum','electronics_beginner','community')
RUNTIME=('static-plan.js','static-records.js','static-bootstrap.js')
ASSETS=('divider-load.png','divider-load.svg','diagnosis-path.png','diagnosis-path.svg',
        'load-current-tradeoff.png','load-current-tradeoff.svg','wechat-qr.jpg')

def relative(text):
    return text.replace('src="/','src="./').replace('href="/','href="./').replace("'/assets/","'./assets/").replace("fetch('/author.json')","fetch('./author.json')")

def public_value(value):
    if isinstance(value,dict):return {k:public_value(v) for k,v in value.items()}
    if isinstance(value,list):return [public_value(v) for v in value]
    if isinstance(value,str) and value.startswith(('/assets/','/?')):return '.'+value
    return value

def build(destination):
    destination=destination.resolve()
    if destination==ROOT or destination in ROOT.parents or destination==ROOT/'web' or destination==ROOT/'config':
        raise ValueError('构建目录不能覆盖项目源码')
    # Derive backup fields from an empty temporary schema, never the real database.
    from radar import core,backup,routes,community
    previous=core.DATA
    try:
        with tempfile.TemporaryDirectory(prefix='static-schema-') as tmp:
            core.DATA=Path(tmp);core.init()
            with core.connect() as db:schemas=backup.schemas(db)
    finally:core.DATA=previous
    config={name:json.loads((ROOT/'config'/f'{name}.json').read_text()) for name in PUBLIC_CONFIG}
    config['community']=community.clean(config['community'])
    config.update(learning_routes=routes.ROUTES,record_schemas=schemas)
    html=(ROOT/'web/index.html').read_text()
    files=set(re.findall(r'(?:src|href)="/([^"?#]+\.(?:js|css))"',html))
    html=html.replace('<script src="/dashboard.js">',''.join(f'<script src="/{name}"></script>' for name in RUNTIME)+'<script src="/dashboard.js">')
    files.add('course-editor.js')
    html=html.replace('<script src="/immersive.js"></script>','<script src="/immersive.js"></script><script src="/course-editor.js"></script>')
    with tempfile.TemporaryDirectory(prefix='static-build-') as tmp:
        stage=Path(tmp)
        for name in sorted(files|set(RUNTIME)):
            if '/' in name:raise ValueError('站点文件列表含未允许或未知入口')
            (stage/name).write_text(relative((ROOT/'web'/name).read_text()))
        (stage/'index.html').write_text(relative(html))
        (stage/'public-config.json').write_text(json.dumps(public_value(config),ensure_ascii=False,separators=(',',':'))+'\n')
        author=json.loads((ROOT/'web/author.json').read_text())
        author={k:author[k] for k in ('enabled','name','description','qr_image') if k in author}
        (stage/'author.json').write_text(json.dumps(public_value(author),ensure_ascii=False)+'\n')
        (stage/'assets').mkdir()
        for name in ASSETS:
            source=ROOT/'web/assets'/name
            if source.is_file() and not source.is_symlink():shutil.copy2(source,stage/'assets'/name)
        shutil.copy2(ROOT/'LICENSE',stage/'LICENSE')
        (stage/'.nojekyll').write_text('')
        # Only replace a previous generated site, never an arbitrary user's folder.
        if destination.exists():
            if not (destination/'.static-build').is_file():raise ValueError('目标目录已存在且不是本站构建产物，请选择空目录')
            shutil.rmtree(destination)
        destination.parent.mkdir(parents=True,exist_ok=True)
        (stage/'.static-build').write_text('Generated by scripts/build_static.py\n')
        shutil.copytree(stage,destination)
    return destination

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=ROOT/'dist');args=p.parse_args()
    print('Public static site:',build(args.output))
