let RAW={},S={}, page=location.hash.slice(1)||'today', filter='all', query='', track='robotics';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=(d=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(d));
const stamp=s=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'尚未检查';
const names={today:'今日学习台',learn:'学习路线',journal:'学习记录',guides:'交互指南',textbook:'电路原理'};
let toastTimeout;function toast(s){clearTimeout(toastTimeout);$('#toast').textContent=s;$('#toast').style.display='block';toastTimeout=setTimeout(()=>$('#toast').style.display='none',3200)}
async function api(path,body){if(body&&['tasks','journal'].includes(path)&&!body.learning_route){const old=body.id?(path==='tasks'?RAW.tasks:RAW.learning_entries)?.find(x=>String(x.id)===String(body.id)):null;body={...body,learning_route:old&&old.track===body.track?SiteRoute.owner(old):body.track===getSiteRoute()?getSiteRoute():body.track};}if(window.StaticSite)return StaticSite.request(path,body);const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'操作失败');return d}
async function refresh(renderIt=true){RAW=await api('state');applySiteRoute();if(renderIt)render();flushAutomaticJournal()}
const btn=(text,action,id='',cls='')=>`<button type="button" class="btn ${cls}" data-action="${action}" data-id="${esc(id)}">${text}</button>`;
const empty=(title,body)=>`<div class="empty"><b>${title}</b>${body}</div>`;
function heading(k,title,sub,actions=''){return `<div class="page-head"><div><div class="eyebrow">${k}</div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`}
function tasksFor(trackId){return S.tasks.filter(t=>t.track===trackId)}
function taskRows(tasks){return tasks.map(t=>`<div class="task ${t.state==='done'?'done':''}"><button class="check" data-action="task-edit" data-id="${t.id}" aria-label="编辑任务：${esc(t.title)}">${t.state==='done'?'✓':t.state==='doing'?'·':''}</button><div class="task-text"><div class="task-title">${esc(t.title)}</div><div class="task-meta">${t.track==='agent'?'AI / Agent':'AI 机器人'} · ${t.minutes} 分钟 · ${t.due?esc(t.due):'未安排日期'} ${t.due&&t.due<day()&&t.state!=='done'?'· 待补课':''}</div>${t.evidence?`<details><summary>查看成果记录</summary><div class="long">${esc(t.evidence)}</div></details>`:''}</div><div class="task-tools">${btn('记时','session',t.id,'small')}${btn('编辑','task-edit',t.id,'small')}</div></div>`).join('')}
function trackCards(){return S.roadmaps.map(r=>{const ts=tasksFor(r.id),done=ts.filter(t=>t.state==='done').length,pct=ts.length?Math.round(done/ts.length*100):0;return `<div class="track-card"><div class="track-top"><span>${esc(r.name)}</span><span>${pct}%</span></div><div class="progress"><i data-width="${pct}"></i></div><small>${done} / ${ts.length} 个个人任务完成 · 6 个能力阶段</small></div>`}).join('')}
function weekBars(){let days=Array.from({length:7},(_,n)=>{let d=new Date();d.setDate(d.getDate()-6+n);let key=day(d);return {label:key.slice(5),value:S.sessions.filter(s=>day(s.created_at)===key).reduce((a,s)=>a+s.minutes,0)}}),max=Math.max(60,...days.map(d=>d.value));return `<div class="week">${days.map(d=>`<div class="day-bar"><span>${d.value||'–'}</span><i data-height="${Math.max(3,d.value/max*55)}"></i><span>${d.label}</span></div>`).join('')}</div>`}
function today(){return renderDashboard()}
function resourceLink(r){return `<li><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)} ↗</a>${r.note?`<small class="resource-note">${esc(r.note)}</small>`:''}</li>`}
function stageResources(s){const groups={};for(const r of s.resources||[])(groups[r.section]??=[]).push(r);return `<details class="curriculum-details"><summary>学习资源 · ${(s.resources||[]).length} 个原文入口</summary><p class="note">课程、文档、工具与硬件参考按原文主题归组，不要求全部学习或购买。</p>${Object.entries(groups).map(([name,rs])=>`<h4>${esc(name)}</h4><ul class="resource-list">${rs.map(resourceLink).join('')}</ul>`).join('')}</details>`}
function learn(){
 const r=S.roadmaps.find(r=>r.id===track)||S.roadmaps[0],ts=tasksFor(r.id);
 if(S[r.id+'_curriculum'])return renderRoboticsCurriculum(r,ts);
 return personalPlanPanel()+heading('LEARNING PATHS','跟着路线，做出自己的作品。','基于 Ronin 两篇六个月路线；资源可直接打开，实践可加入每天的学习计划。',btn('＋ 新建任务','task-new','','primary'))+`<section class="panel roadmap-intro"><span class="badge green">Ronin · 原文六个月结构</span><h2>${esc(r.name)}</h2><p>${esc(r.description)}</p><p class="note">${esc(r.planning_note)}</p><a href="${esc(r.source?.url)}" target="_blank" rel="noopener noreferrer">查看 Ronin 原文 ↗</a><p class="note">${esc(r.source?.resource_status)}</p></section><div class="layout"><section class="panel">${r.stages.map((s,j)=>{const tasks=ts.filter(t=>t.stage===s.id),done=tasks.filter(t=>t.state==='done').length;return `<div class="stage" id="road-stage-${s.id}" tabindex="-1"><span class="stage-number">${j+1}</span><div class="stage-body"><small class="muted">原文第 ${s.month||j+1} 个月</small><h3>${esc(s.name)}</h3><p>${esc(s.outcome)}</p>${renderStageLearning(s)}<div class="practice-grid">${(s.projects||[]).map(p=>`<article class="practice"><span class="badge gray">${esc(p.origin)}</span><h4>${esc(p.title)}</h4><p>${esc(p.instruction)}</p><details><summary>验收条件</summary><p>${esc(p.acceptance)}</p></details>${btn('＋ 安排一次学习','plan-task',p.id,'small')}</article>`).join('')}</div>${stageResources(s)}<div class="panel-head personal-tasks"><h4>我的阶段任务 · ${done} / ${tasks.length}</h4>${btn('＋ 自定义实践','stage-task',s.id,'small')}</div>${btn('记录本阶段学习','journal-stage',s.id,'small')}${taskRows(tasks)}</div></div>`}).join('')}</section><div><section class="panel"><h2>路线进度</h2>${trackCards()}<p class="note">完成比例基于你创建的任务，不代表已经掌握整条路线。完成时需要填写成果记录。</p></section><section class="panel"><h2>每天怎样学</h2><ol class="study-steps"><li>从当前阶段选一个实践，只选当前需要的资源。</li><li>安排一次 45 分钟学习，可修改日期、时长和范围。</li><li>记录实际用时与成果；大项目分多次推进。</li><li>满足验收条件再进入下一阶段；第六阶段选择一个主方向。</li></ol><p class="note">已有基础可凭作品跳过；六个月是文章组织顺序，不是必须完成的期限。浏览、排期和记录均不调用模型。</p></section><section class="panel"><h2>尚未归入阶段</h2>${taskRows(ts.filter(t=>!t.stage))||empty('保持你的节奏','临时任务也可以稍后归入具体阶段。')}</section></div></div>`
}
function planTask(id){for(const r of S.roadmaps)for(const s of r.stages){const p=(s.projects||[]).find(p=>p.id===id);if(p){taskModal({track:r.id,stage:s.id,title:p.title+' · 一次学习',minutes:p.minutes,note:p.origin+'\n实践目标：'+p.instruction+'\n阶段验收：'+p.acceptance+'\n本次范围：请填写今天要完成的一小步。',source_url:p.source_url});return}}}
function render(){const prior=document.activeElement,restore=prior?.closest('#content')?{id:prior.id,action:prior.dataset.action,value:prior.dataset.id}:null;renderSiteShell();if(!Object.hasOwn(names,page)){page='today';const u=new URL(location.href);u.hash=page;history.replaceState(null,'',u);}$('#page-label').textContent=['textbook','guides'].includes(page)?'学习路线 / '+names[page]:names[page];$('#date').textContent=new Date().toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',month:'long',day:'numeric',weekday:'long'});document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===(['textbook','guides'].includes(page)?'learn':page)));$('#content').innerHTML=(window.StaticSite&&['today','journal'].includes(page)?staticRecordsNotice():'')+({today,learn,journal:renderJournal,guides:renderGuides,textbook:renderEETextbook}[page])();document.querySelectorAll('[data-width]').forEach(e=>e.style.width=e.dataset.width+'%');document.querySelectorAll('[data-height]').forEach(e=>e.style.height=e.dataset.height+'px');dashboardBind();journalBind();eeBind();labBind();rcBind();restoreCurriculumLocation();if(restore){const target=restore.id?document.getElementById(restore.id):Array.from(document.querySelectorAll('#content [data-action]')).find(e=>e.dataset.action===restore.action&&e.dataset.id===restore.value);target?.focus({preventScroll:true})}}
function openModal(title,fields,save){$('#form').innerHTML=`<h2 id="modal-title">${esc(title)}</h2>${fields}<p class="error-text" id="form-error" role="alert"></p><div class="actions"><button class="btn" type="button" data-action="close">取消</button><button class="btn primary" type="submit">保存</button></div>`;$('#form').onsubmit=async e=>{e.preventDefault();const b=$('#form button[type=submit]');b.disabled=true;try{const result=await save(Object.fromEntries(new FormData(e.target)),e.target);$('#modal').close();await refresh();if(result!==false)toast(typeof result==='string'?result:'已保存')}catch(err){$('#form-error').textContent=err.message}finally{b.disabled=false}};$('#modal').showModal();document.querySelectorAll('#form label.field').forEach((l,n)=>{const input=l.nextElementSibling;if(input&&/INPUT|SELECT|TEXTAREA/.test(input.tagName)){input.id='modal-field-'+n;l.htmlFor=input.id}});requestAnimationFrame(()=>$('#form input, #form textarea, #form select')?.focus())}
function taskModal(t={}){let selected=t.track||track;let road=S.roadmaps.find(r=>r.id===selected)||S.roadmaps[0];openModal(t.id?'编辑学习任务':'新建学习任务',`<label class="field">任务名称</label><input name="title" required value="${esc(t.title||'')}" placeholder="${getSiteRoute()==='agent'?'例如：运行第一个 Python 应用':'例如：验证分压电路的负载影响'}"><div class="form-grid"><div><label class="field">学习方向</label><select name="track">${S.roadmaps.map(r=>`<option value="${r.id}" ${r.id===selected?'selected':''}>${esc(r.name)}</option>`).join('')}</select></div><div><label class="field">阶段</label><select name="stage"><option value="">暂不归类</option>${road.stages.map(s=>`<option value="${s.id}" ${s.id===t.stage?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div></div><div class="form-grid"><div><label class="field">计划日期</label><input type="date" name="due" value="${esc(t.due??day())}"></div><div><label class="field">预计分钟</label><input type="number" min="1" max="1440" name="minutes" value="${t.minutes||30}"></div></div><label class="field">状态</label><select name="state">${[['todo','待开始'],['doing','进行中'],['done','已完成（需填写成果）']].map(([k,v])=>`<option value="${k}" ${t.state===k?'selected':''}>${v}</option>`).join('')}</select><label class="field">成果与验证证据</label><textarea name="evidence" placeholder="代码链接、实验结果或学习笔记；完成任务时必填。">${esc(t.evidence||'')}</textarea><label class="field">备注</label><textarea name="note">${esc(t.note||'')}</textarea><label class="field">关联原文</label><input name="source_url" type="url" value="${esc(t.source_url||'')}">${t.id?btn('删除此任务','task-delete',t.id,'small'):''}`,d=>api('tasks',{...d,id:t.id,...(t.ee_lesson!==undefined?{ee_lesson:d.track==='robotics'?t.ee_lesson:''}:{}),...(t.electronics_unit!==undefined?{electronics_unit:d.track==='robotics'?t.electronics_unit:''}:{})}));$('#form select[name=track]').onchange=e=>{let r=S.roadmaps.find(r=>r.id===e.target.value);$('#form select[name=stage]').innerHTML='<option value="">暂不归类</option>'+r.stages.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}}
document.addEventListener('click',async e=>{let b=e.target.closest('[data-action],[data-page]');if(!b)return;try{let {action,id}=b.dataset;if(b.dataset.page){location.hash=b.dataset.page;return}if(action==='nav'){location.hash=id;return}if(action==='close')$('#modal').close();if(action==='task-new')taskModal();if(action==='task-edit')taskModal(S.tasks.find(t=>t.id===Number(id)));if(action==='stage-task')taskModal({track,stage:id});if(action==='plan-task')planTask(id);if(action==='track')switchSiteRoute(id);if(action==='filter'){filter=id;render()}if(action==='task-delete'&&confirm('删除这个任务？已记录的学习时长仍会保留。')){await api('tasks/delete',{id:Number(id)});$('#modal').close();await refresh()}if(action==='session'){let t=S.tasks.find(t=>t.id===Number(id));openModal('记录一次学习',`<p class="muted">${esc(t.title)}</p><label class="field">实际投入（分钟）</label><input name="minutes" type="number" min="1" max="1440" value="25" required><label class="field">这次的收获</label><textarea name="note" placeholder="今天做了什么，遇到了什么问题？"></textarea>`,d=>api('sessions',{...d,task_id:Number(id)}))}}catch(err){toast(err.message)}});
window.addEventListener('hashchange',()=>{page=location.hash.slice(1);render();window.scrollTo(0,0)});
refresh().catch(e=>{$('#content').textContent='无法加载学习空间：'+e.message});
