/* Daily study workspace. All interactions are local and model-free. */
const studyStore={key(k){return window.StaticSite?StaticSite.storagePrefix+k:k},read(k,fallback){try{return JSON.parse(localStorage.getItem(this.key(k)))??fallback}catch{return fallback}},write(k,v){try{localStorage.setItem(this.key(k),JSON.stringify(v));return true}catch{return false}}};
let studyDate='',studyView='day',studyTrack='all',studyDraft='',studyBusy=false,studyStarting=false;
let studyGoal=Number(studyStore.read('study-goal',45))||45;
let focusSession=studyStore.read('study-focus',null);
if(focusSession){if(!focusSession.key||!Number.isFinite(focusSession.seconds))focusSession=null;else{focusSession.running=false;focusSession.started=0;studyStore.write('study-focus',focusSession)}}
const dateShift=(key,n)=>{const d=new Date(key+'T12:00:00+08:00');d.setUTCDate(d.getUTCDate()+n);return day(d)};
const trackName=id=>(RAW.roadmaps||S.roadmaps).find(r=>r.id===id)?.name||'学习任务';
function focusSeconds(){return focusSession?Math.min(86400,focusSession.seconds+(focusSession.running?Math.max(0,(Date.now()-focusSession.started)/1000):0)):0}
function persistFocus(){if(focusSession){focusSession.seconds=focusSeconds();focusSession.started=focusSession.running?Date.now():0}return studyStore.write('study-focus',focusSession)}
function studyRows(tasks){return tasks.map(t=>`<article class="study-task ${t.state==='done'?'is-done':''}"><div class="study-task-main"><div class="study-task-meta"><span class="study-state ${t.state}">${{todo:'待开始',doing:'进行中',done:'已完成'}[t.state]}</span><span>${esc(trackName(t.track))} · ${t.minutes} 分钟</span>${t.due&&t.due<day()&&t.state!=='done'?'<span class="study-overdue">待调整计划</span>':''}</div><h3>${esc(t.title)}</h3><div class="study-task-date">${t.due?esc(t.due):'尚未安排日期'}</div>${t.note||t.evidence||t.source_url?`<details><summary>查看${t.state==='done'?'成果':'任务详情与资源'}</summary>${t.note?`<p class="long">${esc(t.note)}</p>`:''}${t.evidence?`<p class="long"><b>成果记录</b><br>${esc(t.evidence)}</p>`:''}${/^https?:\/\//.test(t.source_url)?`<a href="${esc(t.source_url)}" target="_blank" rel="noopener noreferrer">打开学习资源 ↗</a>`:''}</details>`:''}</div><div class="study-task-tools">${t.state!=='done'?btn(focusSession?.taskId===t.id?'回到专注':'开始专注','study-start',t.id,'primary small')+btn('记录成果','study-complete',t.id,'small')+btn('改期','study-reschedule',t.id,'small'):''}${btn('写笔记','journal-task',t.id,'small')}${btn('编辑','task-edit',t.id,'small')}</div></article>`).join('')}
function renderDashboard(){
 studyDate ||= day();const tasks=S.tasks.filter(t=>studyTrack==='all'||t.track===studyTrack),pending=tasks.filter(t=>t.state!=='done');
 const overdue=pending.filter(t=>t.due&&t.due<day()),due=pending.filter(t=>t.due===studyDate),unscheduled=pending.filter(t=>!t.due),upcoming=pending.filter(t=>t.due>day()),done=tasks.filter(t=>t.state==='done');
 const rows=({day:due,overdue,upcoming,unscheduled,done,all:tasks}[studyView]||due).slice().sort((a,b)=>Number(b.state==='doing')-Number(a.state==='doing')||(a.due||'9999').localeCompare(b.due||'9999')||b.id-a.id);
 const sessions=S.sessions.filter(s=>day(s.created_at)===studyDate&&(studyTrack==='all'||tasks.some(t=>t.id===s.task_id))),minutes=sessions.reduce((n,s)=>n+s.minutes,0),completed=done.filter(t=>t.completed_at&&day(t.completed_at)===studyDate).length;
 const next=due.find(t=>t.state==='doing')||due[0]||overdue[0]||S.learning_plan?.tasks.find(t=>t.state!=='done')||unscheduled[0]||upcoming[0],progress=Math.min(100,Math.round(minutes/studyGoal*100));
 const focusTitle=focusSession?S.tasks.find(t=>t.id===focusSession.taskId)?.title:null;
 const days=Array.from({length:7},(_,i)=>dateShift(studyDate,i-3));
 return `<div class="dashboard">${heading('YOUR DAILY PRACTICE','今天，学一点，做出一点。','先选一件事，专注完成，再留下可回顾的成果。',btn('学习记录','nav','journal')+btn('新建任务','study-new'))}
 ${renderDailyLearning(next,focusTitle,minutes,progress,completed)}
  <div class="study-layout"><div><section class="panel study-plan"><div class="panel-head"><h2>我的学习计划</h2><div class="actions">${btn('今天','study-date',day(),'small')}<label class="sr-only" for="study-date-picker">选择计划日期</label><input id="study-date-picker" type="date" value="${studyDate}"></div></div><div class="study-week" aria-label="选择日期">${days.map(d=>{const n=S.tasks.filter(t=>t.due===d&&t.state!=='done'&&(studyTrack==='all'||t.track===studyTrack)).length;return `<button type="button" class="study-day ${d===studyDate?'selected':''}" data-action="study-date" data-id="${d}" aria-pressed="${d===studyDate}" aria-label="${d}，${n} 个待办"><span>${d===day()?'今天':new Date(d+'T12:00:00+08:00').toLocaleDateString('zh-CN',{weekday:'short'})}</span><b>${d.slice(5).replace('-','/')}</b><small>${n?n+' 项':'—'}</small></button>`}).join('')}</div>
 <form id="study-quick" class="study-quick"><label class="sr-only" for="study-title">快速添加任务</label><input id="study-title" name="title" required maxlength="300" placeholder="记下这一天要做的一小步…" value="${esc(studyDraft)}"><input type="hidden" name="track" value="${getSiteRoute()}"><button type="submit" class="btn primary" ${studyBusy?'disabled':''}>${studyBusy?'添加中…':'添加'}</button><small>安排在 ${esc(studyDate)} · 默认 30 分钟，可在编辑中修改</small><p id="study-quick-error" role="alert"></p></form>
 <div class="study-filters"><div class="study-tabs" aria-label="任务状态筛选">${[['day','当日',due.length],['overdue','待调整',overdue.length],['upcoming','之后',upcoming.length],['unscheduled','未排期',unscheduled.length],['done','已完成',done.length],['all','全部',tasks.length]].map(([v,l,n])=>`<button type="button" class="${studyView===v?'selected':''}" data-action="study-view" data-id="${v}" aria-pressed="${studyView===v}">${l} <span>${n}</span></button>`).join('')}</div></div>
 <div id="study-tasks">${rows.length?studyRows(rows):`<div class="study-empty"><span class="study-empty-icon" aria-hidden="true">✓</span><h3>${studyView==='day'?'这一天还没有待办':'这里暂时没有任务'}</h3><p>${studyView==='day'?'在上方记下一小步，或从路线中选择一个实践。':'换个分类看看，也可以添加新的学习任务。'}</p>${studyView==='day'&&overdue.length?btn('查看 '+overdue.length+' 项待调整计划','study-view','overdue','small'):btn('探索学习路线','nav','learn','small')}</div>`}</div></section>
 ${journalDashboard()}</div>
 <aside class="study-sidebar"><section class="panel"><div class="panel-head"><h2>这一周的积累</h2><span class="muted">分钟</span></div>${weekBars()}<p class="note">${esc(siteRouteName())} · 过去 7 天的实际记录。每天学一点，也值得被看见。</p></section><section class="panel"><div class="panel-head"><h2>${studyDate===day()?'今日':esc(studyDate.slice(5))}回顾</h2><span class="badge gray">${sessions.length} 次</span></div>${sessions.length?sessions.slice().reverse().map(s=>{const t=S.tasks.find(t=>t.id===s.task_id);return `<article class="study-review"><div><b>${s.minutes} 分钟</b><time>${stamp(s.created_at)}</time></div><h3>${esc(t?.title||'已删除的任务')}</h3><p class="long">${esc(s.note||'本次学习已自动记录，可在记录本补充想法。')}</p>${t?btn('查看任务','task-edit',t.id,'small'):''}</article>`}).join(''):`<div class="study-review-empty">还没有学习记录。<br>结束一次专注后，在这里回顾收获。</div>`}</section><section class="panel study-tip"><h2>完成，比学完更具体</h2><p>读完一篇文章之后，试着留下一段代码、一张实验截图，或一条你能解释清楚的结论。</p>'<a href="#learn">选择下一块课程 ↗</a>'</section></aside></div></div>`;
}
function drawFocus(){const dock=document.getElementById('focus-dock');if(!dock)return;document.body.classList.toggle('has-focus',!!focusSession);if(!focusSession){dock.innerHTML='';return}const t=RAW.tasks?.find(t=>t.id===focusSession.taskId);dock.innerHTML=`<div class="focus-bar"><div class="focus-info"><span class="study-kicker">${focusSession.running?'正在专注':'已暂停 · 随时继续'}</span><div class="route-focus-label">${esc(t?SiteRoute.definitions[SiteRoute.owner(t)].name:'原任务')} · ${t&&SiteRoute.owner(t)!==getSiteRoute()?'另一条路线的计时':'当前路线'}</div><b>${esc(t?.title||'任务已删除，请结束本次计时')}</b></div>${t&&SiteRoute.owner(t)!==getSiteRoute()?`<button type="button" class="btn small" data-site-route="${SiteRoute.owner(t)}">返回该路线</button>`:''}<output id="focus-clock" aria-label="专注时长"></output><div class="actions">${btn(focusSession.running?'暂停':'继续','study-toggle','','small')}${btn('结束并自动记录','study-finish','','primary small')}${btn('放弃','study-discard','','small')}</div></div>`;updateFocusClock()}
async function finishFocusAutomatically(){
 if(!focusSession)return;
 persistFocus();focusSession.running=false;focusSession.started=0;persistFocus();drawFocus();
 const seconds=Math.floor(focusSeconds()),saved=focusSession;
 saved.finishPayload ||= {task_id:saved.taskId,session_key:saved.key,minutes:Math.floor(seconds/60),timer_seconds:seconds,complete:false};persistFocus();
 await api('study/finish',saved.finishPayload);
 focusSession=null;studyStore.write('study-focus',null);drawFocus();await refresh();
 toast('本次学习已自动记录，无需填写；想法可以稍后补充');
}
function updateFocusClock(){const el=document.getElementById('focus-clock');if(el){const s=Math.floor(focusSeconds());el.textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}}
function dashboardBind(){drawFocus();const form=$('#study-quick');if(form){$('#study-title').oninput=e=>studyDraft=e.target.value;form.onsubmit=async e=>{e.preventDefault();if(studyBusy)return;const data=Object.fromEntries(new FormData(form));if(!data.title.trim())return;studyBusy=true;const submit=form.querySelector('[type=submit]');submit.disabled=true;submit.textContent='添加中…';try{await api('tasks',{...data,due:studyDate,minutes:30});studyDraft='';studyView='day';if(studyTrack!=='all')studyTrack=data.track;await refresh();$('#study-title')?.focus();toast('已加入 '+studyDate+' 的计划')}catch(err){$('#study-quick-error').textContent=err.message}finally{studyBusy=false;if(submit.isConnected){submit.disabled=false;submit.textContent='添加'}const current=$('#study-quick [type=submit]');if(current){current.disabled=false;current.textContent='添加'}}}}if($('#study-date-picker'))$('#study-date-picker').onchange=e=>{if(e.target.value){studyDate=e.target.value;studyView='day';render()}};if($('#study-track-filter'))$('#study-track-filter').onchange=e=>{studyTrack=e.target.value;render()}}
async function startStudy(id){if(studyStarting)return;studyStarting=true;try{const t=RAW.tasks.find(t=>t.id===Number(id));if(t&&SiteRoute.owner(t)!==getSiteRoute())switchSiteRoute(SiteRoute.owner(t));if(!t||t.state==='done')return;if(focusSession){if(focusSession.taskId!==t.id){toast('先结束当前专注，再开始另一件事');return}$('#focus-dock button')?.focus();return}await api('tasks',{...t,state:'doing'});focusSession={key:crypto.randomUUID(),taskId:t.id,seconds:0,running:true,started:Date.now()};const saved=persistFocus();await refresh();toast(saved?'开始专注，按你的节奏来':'计时已开始；浏览器存储不可用，刷新可能丢失计时')}finally{studyStarting=false}}
function finishStudy(t,fromTimer=false){if(!t){toast('任务已删除，可以放弃当前计时');return}if(fromTimer){persistFocus();focusSession.running=false;focusSession.started=0;persistFocus();drawFocus()}const key=fromTimer?focusSession.key:crypto.randomUUID();openModal(fromTimer?'收好这次学习的成果':'记录成果，完成任务',`<p class="muted">${esc(t.title)}</p><label class="field">实际学习分钟</label><input type="number" name="minutes" min="0" max="1440" required value="${fromTimer?Math.floor(focusSeconds()/60):0}"><p class="note">计时仅供参考，请确认实际投入。0 分钟不会新增时长记录。</p><label class="field">本次收获 / 下次继续什么</label><textarea name="note" maxlength="1000" placeholder="今天解决了什么？下一步从哪里继续？"></textarea><label class="toggle-line"><input name="complete" type="checkbox" ${fromTimer?'':'checked'}>这项任务已经完成</label><label class="field">成果与验证证据<span id="study-evidence-hint">${fromTimer?'（完成任务时必填）':'（必填）'}</span></label><textarea name="evidence" maxlength="5000" ${fromTimer?'':'required'} placeholder="代码链接、实验结果、可以解释清楚的一条结论…">${esc(t.evidence)}</textarea>`,async(d,f)=>{await api('study/finish',{...d,task_id:t.id,session_key:key,complete:f.complete.checked});if(fromTimer){focusSession=null;persistFocus();drawFocus()}});$('#form input[name=complete]').onchange=e=>{$('#form textarea[name=evidence]').required=e.target.checked;$('#study-evidence-hint').textContent=e.target.checked?'（必填）':'（完成任务时必填）'}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action^="study-"]');if(!b||b.disabled)return;const {action,id}=b.dataset;try{if(action==='study-new')taskModal({due:studyDate||day(),track:getSiteRoute()});if(action==='study-date'){studyDate=id;studyView='day';render()}if(action==='study-view'){studyView=id;render()}if(action==='study-start'){b.disabled=true;await startStudy(id)}if(action==='study-toggle'&&focusSession){if(focusSession.finishPayload){toast('上次记录等待保存，请先重试结束学习');return}persistFocus();focusSession.running=!focusSession.running;focusSession.started=focusSession.running?Date.now():0;persistFocus();drawFocus()}if(action==='study-finish'&&focusSession){b.disabled=true;await finishFocusAutomatically();}if(action==='study-complete'){const t=S.tasks.find(t=>t.id===Number(id));finishStudy(t,focusSession?.taskId===t?.id)}if(action==='study-discard'&&focusSession){openModal('放弃本次计时？','<p>本次未保存的时长将被清除，任务仍然保留。</p>',async()=>{focusSession=null;persistFocus();drawFocus()});$('#form button[type=submit]').textContent='确认放弃'}if(action==='study-reschedule'){const t=S.tasks.find(t=>t.id===Number(id));openModal('调整计划日期',`<p>${esc(t.title)}</p><label class="field">计划日期（留空则不排期）</label><input name="due" type="date" value="${esc(t.due)}"><div class="actions">${btn('今天','study-pick-date',day(),'small')}${btn('明天','study-pick-date',dateShift(day(),1),'small')}${btn('暂不排期','study-pick-date','','small')}</div>`,d=>api('tasks',{...t,due:d.due}))}if(action==='study-pick-date')$('#form input[name=due]').value=id;if(action==='study-goal')openModal('设定每日学习目标','<p class="note">只用于安排自己的节奏，可随时调整。保存在当前浏览器。</p><label class="field">每天投入分钟</label><input name="goal" type="number" min="1" max="1440" step="1" required value="'+studyGoal+'">',async d=>{studyGoal=Number(d.goal);if(!studyStore.write('study-goal:'+getSiteRoute(),studyGoal))throw Error('浏览器存储不可用，无法保存目标')})}catch(err){toast(err.message)}finally{if(b.isConnected)b.disabled=false}});
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='n'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!e.repeat&&page==='today'&&!$('#modal').open&&!e.target.closest('input,textarea,select,[contenteditable]')){e.preventDefault();$('#study-title')?.focus()}});
window.addEventListener('pagehide',persistFocus);
setInterval(()=>{if(focusSession){updateFocusClock();if(focusSession.running)persistFocus()}},1000);
