/* Original guided exercises; explicit interactions save objective model observations. */
const ElectronicsLessons={
 measurement:{name:'接线与测量',question:'表笔接在哪里，决定你测到什么。',prediction:'先猜：交换红黑表笔会怎样？电流档能直接跨在电源两端吗？',scope:'限定为理想 5 V 电源、1 kΩ + 2 kΩ 串联网络。面包板只演示四组五孔接点，不代表所有型号的电源轨。',source:'https://learn.sparkfun.com/tutorials/how-to-use-a-breadboard',challenge:'先测 M 对 G 的电压，再交换表笔；最后断开 P—A，用电流档桥接断口。',options:['电流表应跨在电源两端','电流表应串入待测支路'],answer:1,explain:'电压表并联测电位差；电流表串联测支路电流。换档时也要检查插孔、量程与接法。'},
 switching:{name:'开关与驱动',question:'3.3 V 控制信号，怎样控制另一条供电回路？',prediction:'先猜：增大基极电阻，会改善还是削弱负载驱动条件？',scope:'NPN 低端开关的预算模型：VBE = 0.7 V、饱和 VCE = 0.2 V，按强制 β = 10 预算。不是实际晶体管曲线；8 mA 是本练习设定的 GPIO 预算，真实限制查器件手册。',source:'https://e2e.ti.com/cfs-file/__key/communityserver-discussions-components-files/196/slyy168.pdf',challenge:'让负载达到导通预算，同时保持基极电流不超过本练习 8 mA；比较 100 Ω 与 1 kΩ 负载。',options:['负载电流由 GPIO 直接提供','GPIO 控制开关，负载主要由独立电源供电'],answer:1,explain:'控制回路与负载回路分工不同。还要检查共地、晶体管额定值、热耗散与感性负载的关断保护。'},
 logic:{name:'逻辑与按键',question:'一次按下，为什么可能被程序识别成多次？',prediction:'先猜：提高稳定时间门槛，会减少重复触发，还是让响应更快？',scope:'逻辑门与高有效 SR 锁存器采用理想布尔模型。去抖使用固定示例波形与稳定时间算法，不是某个按键的实测。',source:'https://docs.arduino.cc/built-in-examples/digital/Debounce/',challenge:'比较 0、5、15、30 ms 去抖门槛；检查触发次数与边沿延迟。再尝试锁存器的置位、保持与复位。',options:['只判断电平变高就能保证只触发一次','等待电平持续稳定，再接受状态变化'],answer:1,explain:'机械抖动会制造多个边沿。稳定时间去抖能过滤短变化，也会延迟响应；门槛不能无限增大。'},
 interface:{name:'程序输入输出',question:'改变传感器电压，程序会立刻知道吗？',prediction:'先猜：没有再次执行读取，旧的采样值会自动改变吗？',scope:'理想 10 位 ADC，码宽为 Vref / 1024；仅模拟“采样 → 阈值判断 → 指示输出”，不是 Arduino 固件执行器。输出为逻辑指示，不直接驱动电机。',source:'https://docs.arduino.cc/learn/microcontrollers/analog-input/',challenge:'先执行一次读取，再改变电压但不读取；比较当前输入与旧采样。然后打开自动采样，检查阈值附近的输出。',options:['程序只有重新采样后才获得新的读数','传感器变化会自动重写上一次读数'],answer:0,explain:'物理输入、采样时刻与程序状态要分开。程序还需处理参考地、引脚模式、采样频率和异常输入。'},
 soldering:{name:'连接质量检查',question:'看起来亮，就一定连接可靠吗？',prediction:'先猜：只看外观，能排除短路和接触不良吗？',scope:'原创示意与预设故障检查，不是焊接过程仿真或你的硬件测量。真实焊接仍需实物操作；无铅焊点的表面状态不能单独作为质量结论。',source:'https://learn.adafruit.com/adafruit-guide-excellent-soldering/common-problems',challenge:'选一个示例，分别检查本节点通断、相邻节点隔离与机械连接，再决定是否需要返修。',options:['亮度足以证明焊点可靠','综合接点外观、电气隔离与机械检查'],answer:1,explain:'导通只证明当前测量条件下的连接状态。外观、电气、机械检查相互补充，仍不能代替运行与长期可靠性验证。'},
 exploration:{name:'电磁感应',question:'磁铁停在线圈旁边，还会一直发电吗？',prediction:'先猜：接近与远离线圈时，感应电压的方向相同吗？',scope:'采用假设磁通 Φ(x) = 0.001 exp(−x²) Wb 的离散模型，x 为归一化位置；每次采样 Δt = 0.1 s。不是实际线圈几何、输出功率或无线电仿真。',source:'https://openstax.org/books/university-physics-volume-2/pages/13-1-faradays-law',challenge:'采样磁铁接近、停住、离开三个过程；反转磁极或增加匝数，比较电压方向和幅度。',options:['静止磁通本身就持续产生感应电压','磁通随时间变化才产生感应电压'],answer:1,explain:'E = −N ΔΦ / Δt。负号表示感应方向反抗磁通变化；有电压并不自动意味着能输出足够的负载功率。'}
};
if(typeof module!=='undefined')module.exports=ElectronicsLessons;
if(typeof document!=='undefined'){
 const M=ElectronicsModels;
 const state={
  measurement:{mode:'V',red:'M',black:'G',power:true,broken:false,hole:'L1-1'},
  switching:{on:true,rb:1000,load:100,ground:true,inductive:true,diode:true},
  logic:{view:'gate',gate:'and',a:false,b:false,s:false,r:false,q:0,delay:15,time:130},
  interface:{voltage:1.5,reference:3.3,threshold:512,ground:true,input:true,last:null,trace:[]},
  soldering:{scene:'normal',checks:[]},
  exploration:{position:-3,previous:-3,turns:100,polarity:1,history:[]}
 };
 const initial=JSON.parse(JSON.stringify(state));
 let active='',timer=0,running=false;
 const number=(n,d=2)=>Number(n).toFixed(d);
 const checked=v=>v?'checked':'';
 function select(key,label,choices,value){return `<label class="el-field">${label}<select data-el="${key}">${Object.entries(choices).map(([v,t])=>`<option value="${v}" ${String(value)===v?'selected':''}>${t}</option>`).join('')}</select></label>`;}
 function range(key,label,value,min,max,step=1,unit=''){return `<label class="lab-control" for="el-${key}"><span>${label}<output data-value="${key}">${value}${unit}</output></span><input id="el-${key}" data-el="${key}" type="range" value="${value}" min="${min}" max="${max}" step="${step}"></label>`;}
 function toggle(key,label,value){return `<label class="lab-toggle"><input type="checkbox" data-el="${key}" ${checked(value)}>${label}</label>`;}
 function button(action,label,primary=false){return `<button type="button" class="btn ${primary?'primary':''}" data-el-action="${action}">${label}</button>`;}
 function svg(body,label,box='0 0 440 250'){return `<svg class="el-svg" viewBox="${box}" role="img" aria-label="${esc(label)}">${body}</svg>`;}
 function text(x,y,label,cls=''){return `<text x="${x}" y="${y}" class="${cls}">${esc(label)}</text>`;}
 function wire(path,on=false){return `<path d="${path}" class="el-wire ${on?'el-on':''}"/>`;}
 function metrics(rows){return `<dl class="el-metrics">${rows.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`;}
 function controls(id){const s=state[id];
  if(id==='measurement')return select('mode','万用表档位',{V:'直流电压 V',R:'电阻 Ω',I:'直流电流 mA'},s.mode)+select('red','红表笔',{P:'P · 电源正端',A:'A · 电阻上端',M:'M · 两电阻中点',G:'G · 参考地'},s.red)+select('black','黑表笔',{P:'P · 电源正端',A:'A · 电阻上端',M:'M · 两电阻中点',G:'G · 参考地'},s.black)+toggle('power','接入 5 V 电源',s.power)+toggle('broken','断开 P—A，预留电流测量口',s.broken);
  if(id==='switching')return toggle('on','控制信号为高电平（3.3 V）',s.on)+range('rb','基极电阻 Rb',s.rb,100,10000,100,' Ω')+range('load','负载等效电阻',s.load,50,1000,50,' Ω')+toggle('ground','控制地与负载地相连',s.ground)+toggle('inductive','负载包含线圈',s.inductive)+toggle('diode','线圈两端接反向续流二极管',s.diode);
  if(id==='logic')return select('view','观察内容',{gate:'逻辑门',latch:'SR 锁存',bounce:'按键去抖'},s.view)+(s.view==='gate'?select('gate','逻辑关系',{and:'AND · 与',or:'OR · 或',xor:'XOR · 异或',nand:'NAND · 与非'},s.gate)+toggle('a','输入 A = 1',s.a)+toggle('b','输入 B = 1',s.b):s.view==='latch'?toggle('s','S = 1 · 置位',s.s)+toggle('r','R = 1 · 复位',s.r)+button('latch-reset','从 Q = 0 重新开始'):range('delay','持续稳定门槛',s.delay,0,40,1,' ms')+range('time','观察到的时刻',s.time,0,130,1,' ms')+'<div class="actions">'+button('play','播放波形',true)+button('restart','回到起点')+'</div>');
  if(id==='interface')return range('voltage','当前传感器电压',s.voltage,0,5,.05,' V')+select('reference','ADC 参考电压',{'3.3':'3.3 V','5':'5 V'},s.reference)+range('threshold','点亮阈值',s.threshold,0,1023,1)+toggle('ground','传感器与控制板共地',s.ground)+toggle('input','采样引脚设为 INPUT',s.input)+'<div class="actions">'+button('sample','执行一次读取',true)+button('play','自动采样')+'</div>';
  if(id==='soldering')return select('scene','选择待检查的接点',{normal:'接点 A',bridge:'接点 B',weak:'接点 C'},s.scene)+'<p>先观察示意，再逐项检查。检查结果来自练习预设。</p><div class="el-check-actions">'+['continuity','isolation','mechanical'].map((key,i)=>button('check-'+key,['检查同一节点通断','检查相邻节点隔离','检查机械连接'][i])).join('')+'</div>'+button('clear-checks','清空本次检查');
  return range('position','磁铁位置 x',s.position,-3,3,.25)+range('turns','线圈匝数 N',s.turns,50,500,50)+select('polarity','磁极方向',{'1':'方向一','-1':'反转磁极'},s.polarity)+'<div class="actions">'+button('induct-sample','采样当前位置',true)+button('play','播放穿过线圈')+button('restart','从左侧重新开始')+'</div><p>移动位置后点击采样。连续对同一位置采样，检查电压是否归零。</p>';
 }
 function measurementView(s){const m=M.meter(s),group=M.breadboardGroup(s.hole);
  const board=`<div class="el-breadboard"><p><b>先认节点：</b>点击一个孔，查看与它直接连通的孔。</p>${['L','R'].map(side=>`<div class="el-board-half">${[1,2].map(row=>`<div class="el-hole-row"><span>${side}${row}</span>${[1,2,3,4,5].map(col=>{const id=side+row+'-'+col;return `<button class="el-hole ${M.breadboardGroup(id)===group?'connected':''}" data-el-hole="${id}" aria-label="${id}${id===s.hole?'，当前选择':''}" aria-pressed="${id===s.hole}">${col}</button>`}).join('')}</div>`).join('')}</div>`).join('<div class="el-trench">中缝 · L / R 两侧不直接连通</div>')}<p class="note">当前节点：${group}。不同排不直接连通；实际电源轨可能分段，要用通断档确认。下方是独立原理图，不与上方孔位自动接线。</p></div>`;
  const drawing=svg(wire('M70 80H120')+wire(s.broken?'M120 80L144 60M160 80H190':'M120 80H190')+'<circle cx="70" cy="150" r="23" class="el-part"/>'+wire('M70 80V127M70 173V220H370V80H350')+'<rect x="190" y="68" width="65" height="24" class="el-part"/>'+wire('M255 80H285')+'<rect x="285" y="68" width="65" height="24" class="el-part"/>'+wire('M270 80V150')+text(45,154,s.power?'5 V':'移除')+text(100,52,'P')+text(161,52,'A')+text(205,52,'1 kΩ')+text(300,52,'2 kΩ')+text(258,176,'M')+text(355,244,'G · 0 V')+text(90,205,`红 ${s.red} · 黑 ${s.black}`),`测量网络，${s.broken?'P—A 断开':'P—A 连通'}，红表笔${s.red}黑表笔${s.black}`);
  return board+drawing+metrics([['当前读数',esc(m.label)],['测量状态',m.valid?'模型可计算':'检查接法']])+`<p class="lab-insight">${esc(m.reason)}</p>`;
 }
 function driverView(s){const m=M.driver(s),warnings=[];
  if(!m.valid)warnings.push('缺少共同参考地，控制电压相对发射极不确定；不预测负载状态。');
  if(m.gpioOver)warnings.push('基极电流超过本练习 8 mA GPIO 预算。');
  if(s.on&&m.valid&&!m.saturated)warnings.push('按 β=10 的预算尚不足以保证饱和；实际电流需器件模型或测量确认。');
  if(s.inductive&&!s.diode)warnings.push('感性负载关断需要泄放能量路径；未接续流保护。本图不预测尖峰幅度。');
  const drawing=svg(wire('M285 35V65')+'<rect x="258" y="65" width="54" height="55" class="el-part"/>'+wire('M285 120V160',m.saturated)+'<circle cx="285" cy="180" r="25" class="el-part"/>'+wire('M270 165V195M270 172L285 160M270 188L285 200M285 200V235',m.saturated)+'<path d="M285 200L274 196L280 189Z" class="el-arrow"/>'+wire('M60 180H115M180 180H260',s.on)+'<rect x="115" y="168" width="65" height="24" class="el-part"/>'+wire(s.ground?'M60 215V235H285':'M60 215V235H160M185 235H285')+text(250,25,'+5 V')+text(68,154,s.on?'3.3 V':'0 V')+text(126,157,'Rb')+text(165,88,s.inductive?'线圈':'负载')+text(165,113,s.load+' Ω')+text(320,187,'NPN')+text(80,260,s.ground?'控制地与负载地相连':'两侧缺少共同参考地')+(s.inductive&&s.diode?wire('M285 48H365V138H285')+'<rect x="352" y="65" width="26" height="55" class="el-part"/>'+text(380,79,'K')+text(380,120,'A'):''),`NPN低端驱动，${m.saturated?'满足导通预算':'尚未满足导通预算'}`,'0 0 440 280');
  return drawing+metrics([['基极电流',m.base===null?'不确定':(m.base*1000).toFixed(2)+' mA'],['目标负载电流',(m.required*1000).toFixed(2)+' mA'],['10 × Ib 预算',m.budget===null?'不确定':(m.budget*1000).toFixed(2)+' mA']])+`<p class="lab-insight">${warnings.length?warnings.join(' '):!s.on?'控制信号关闭，稳态负载电流为零。线圈关断瞬间的续流不由此直流模型计算。':'满足本练习的导通电流预算，仍需对照实际元件额定值。'}${s.inductive&&s.diode?' 二极管 K（阴极）接 +5 V，A（阳极）接开关端，正常供电时反偏。':''}</p>`;
 }
 function logicView(s){
  if(s.view==='gate'){const value=M.gate(s.gate,s.a,s.b);return svg(wire('M45 85H140M45 165H140M290 125H380',!!value)+'<rect x="140" y="60" width="150" height="130" rx="20" class="el-part"/>'+text(178,135,s.gate.toUpperCase(),'el-big')+text(52,70,'A = '+Number(s.a))+text(52,193,'B = '+Number(s.b))+`<circle cx="380" cy="125" r="22" class="el-led ${value?'is-on':''}"/>`+text(340,177,'Q = '+value),'逻辑门输出'+value)+`<table class="el-truth"><caption>真值表 · 当前输入所在行高亮</caption><thead><tr><th>A</th><th>B</th><th>Q</th></tr></thead><tbody>${[[0,0],[0,1],[1,0],[1,1]].map(([a,b])=>`<tr class="${a===Number(s.a)&&b===Number(s.b)?'current':''}"><td>${a}</td><td>${b}</td><td>${M.gate(s.gate,!!a,!!b)}</td></tr>`).join('')}</tbody></table>`;}
  if(s.view==='latch')return svg(wire('M45 85H140M45 165H140M290 125H380')+'<rect x="140" y="60" width="150" height="130" rx="20" class="el-part"/>'+text(170,115,'SR 锁存')+text(175,150,'保持状态')+text(45,70,'S = '+Number(s.s))+text(45,193,'R = '+Number(s.r))+text(335,125,'Q '+(s.q===null?'?':s.q),'el-big'),'锁存输出'+(s.q===null?'不确定':s.q))+`<p class="lab-insight">${s.s&&s.r?'S = R = 1 为禁用输入；释放后的状态不能由此模型保证，请单独置位或复位。':s.q===null?'先前进入禁用状态。单独置位或复位后，再观察保持。':!s.s&&!s.r?'S = R = 0，保留之前的 Q。输入撤销后，状态仍然存在。':s.s?'S = 1，置位 Q = 1。':'R = 1，复位 Q = 0。'}</p>`;
  const m=M.bounce(s.delay,s.time),plot=(series,y)=>{let d=`M45 ${y+24}`;for(const [t,v] of series)d+=`H${45+t/130*350}V${y+(v?0:24)}`;return d+`H${45+s.time/130*350}`;};
  return svg(text(45,30,'固定示例 · 高电平视为按下')+text(45,63,'原始输入')+`<path d="${plot(m.raw,78)}" class="el-wave el-raw"/>`+text(45,140,'去抖输出')+`<path d="${plot(m.filtered,155)}" class="el-wave"/>`+wire('M45 205H395')+text(45,232,'0 ms')+text(335,232,'130 ms')+`<path d="M${45+s.time/130*350} 65V205" class="el-cursor"/>`,'按键原始与去抖波形')+metrics([['原始上升沿',m.rawCount+' 次'],['接受的按下',m.count+' 次'],['当前时刻',s.time+' ms']])+`<p class="lab-insight">状态需持续稳定 ${s.delay} ms 才接受。完整示例只有一次有意按下；门槛太短可能仍会重复触发，太长也会漏掉短按。</p>`;
 }
 function interfaceView(s){const sample=s.last;return svg('<rect x="30" y="82" width="100" height="76" rx="10" class="el-part"/>'+text(42,112,'传感器')+text(42,140,number(s.voltage)+' V')+wire('M130 120H170')+'<rect x="170" y="65" width="125" height="110" rx="10" class="el-part"/>'+text(195,95,'10 位 ADC')+text(185,129,sample?.valid?'读数 '+sample.code:'尚无有效读数')+text(185,155,'阈值 '+s.threshold)+wire('M295 120H363',!!sample?.output)+`<circle cx="385" cy="120" r="22" class="el-led ${sample?.output?'is-on':''}"/>`+text(335,170,'逻辑输出')+text(45,222,sample?'上次采样 '+(sample.valid?sample.voltage.toFixed(2)+' V':'输入无效'):'还没有执行读取'),'传感器采样与程序输出')+`<pre class="el-code">raw = analogRead(inputPin)
+output = (raw >= threshold)
+digitalWrite(indicator, output)</pre>`.replace(/^\+/gm,'')+`<p class="lab-insight">${!s.ground?'先连接共同参考地，当前输入相对 ADC 的电位不确定。':!s.input?'采样引脚模式不正确；本练习不预测输出模式下的读数。':s.voltage>s.reference?'输入超过参考范围，本练习拒绝采样；实际板卡还须检查允许输入范围，不能照此过压接线。':sample?.valid?`上次码值 ${sample.code}，${sample.output?'达到':'未达到'}当时阈值 ${sample.threshold}，输出${sample.output?'高':'低'}。当前控制参数改变后，需要再次执行读取。`:'先执行一次读取，获得码值并更新逻辑输出。'}</p>`+(s.trace.length?`<ol class="el-trace" aria-label="最近五次执行记录">${s.trace.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>`:'');}
 function solderView(s){const bridge=s.scene==='bridge',weak=s.scene==='weak';return svg('<rect x="50" y="180" width="340" height="35" class="el-board"/>'+[130,305].map(x=>`<ellipse cx="${x}" cy="173" rx="44" ry="12" class="el-pad"/><path d="M${x-30} 170Q${x} ${weak?160:95} ${x+30} 170Z" class="el-solder ${weak?'el-weak':''}"/><path d="M${x} 60V172" class="el-lead"/>`).join('')+(bridge?'<path d="M158 166Q217 148 278 166" class="el-bridge"/>':'')+text(85,40,'节点 1')+text(260,40,'节点 2')+text(65,244,'外观仅作线索，结合其他检查。'),'两个焊接节点的检查示意')+`<ul class="el-check-results">${s.checks.map(k=>`<li>${k==='continuity'?'同一节点：'+(weak?'接触状态不稳定（预设）':'当前导通（预设）'):k==='isolation'?'相邻节点：'+(bridge?'导通，发现非预期连接（预设）':'未导通（预设）'):'机械检查：'+(weak?'接点松动（预设）':'本次轻拉未见松动（预设）')}</li>`).join('')}</ul><p class="lab-insight">${!s.checks.length?'请选择检查方法，再判断连接状态。':bridge&&s.checks.includes('isolation')?'相邻节点本应隔离却导通，应定位桥连并返修；断电检查后再复测。':weak&&s.checks.some(k=>k!=='isolation')?'本例预设连接不稳定，需要返修和复检；真实接点不能只凭“暗”就判为虚焊。':s.checks.length===3?'本次三项预设检查未见异常，不代表实际焊接已通过或长期可靠。':'还可以补充其他检查，避免单一证据下结论。'}</p>`;}
 function inductionView(s){const last=s.history.at(-1),position=80+(s.position+3)/6*260;return svg('<path d="M180 80C140 80 140 170 180 170S220 80 180 80M200 80C160 80 160 170 200 170S240 80 200 80M220 80C180 80 180 170 220 170S260 80 220 80" class="el-coil"/>'+`<rect x="${position-38}" y="108" width="38" height="28" class="el-magnet-n"/><rect x="${position}" y="108" width="38" height="28" class="el-magnet-s"/>`+text(position-25,128,s.polarity===1?'N':'S')+text(position+15,128,s.polarity===1?'S':'N')+wire('M70 205H370')+text(70,232,'−3')+text(205,232,'0')+text(355,232,'+3')+text(55,45,'磁通变化 → 感应电压'),'磁铁与线圈相对位置')+metrics([['上次采样电压',last?number(last.emf,3)+' V':'尚未采样'],['上次磁通',last?number(last.flux*1000,3)+' mWb':'尚未采样']])+`<p class="lab-insight">${last?Math.abs(last.emf)<1e-10?'相邻两次采样磁通相同，感应电压为零。':`上次从 x=${number(last.previous)} 到 ${number(last.position)}，Δt=0.1 s；电压为${last.emf>0?'正':'负'}，方向按设定的线圈参考方向。`:'先移动位置，再采样；记录接近和远离时的电压方向。'}</p>`+(s.history.length?`<ol class="el-trace" aria-label="最近五次感应采样">${s.history.slice(-5).map(h=>`<li>x ${number(h.previous)} → ${number(h.position)}：${number(h.emf,3)} V</li>`).join('')}</ol>`:'');}
 const views={measurement:measurementView,switching:driverView,logic:logicView,interface:interfaceView,soldering:solderView,exploration:inductionView};
 function renderElectronicsLesson(id){active=id;const l=ElectronicsLessons[id];return `<section class="panel circuit-lab extended-lab" data-lesson="${id}" aria-labelledby="el-title"><div class="lab-heading"><div><span class="study-kicker">${l.name} · 先预测，再验证</span><h2 id="el-title">${l.question}</h2></div><span class="badge">原创教学练习</span></div><p class="el-prediction">${l.prediction}</p><div class="lab-workspace"><div class="lab-controls" id="el-controls">${controls(id)}</div><div class="lab-visual" id="el-visual"></div></div><div id="el-feedback" role="status" aria-live="polite"></div><details class="el-challenge"><summary>试一试，再解释</summary><p>${l.challenge}</p><label class="el-field">你的理解<select id="el-answer"><option value="">选一个判断</option>${l.options.map((v,i)=>`<option value="${i}">${v}</option>`).join('')}</select></label>${button('answer','检查我的理解')}<p id="el-answer-feedback" role="status"></p></details><div class="lab-bottom"><p>操作后的模型观察会自动保存到学习记录。${l.scope} <a href="${l.source}" target="_blank" rel="noopener noreferrer">原理参考 ↗</a></p>${button('record','保存当前观察',true)}</div></section>`;}
 function update(announce=false){if(!document.querySelector('.extended-lab'))return;document.getElementById('el-visual').innerHTML=views[active](state[active]);const play=document.querySelector('[data-el-action=play]');if(play)play.textContent=running?'暂停':active==='interface'?'自动采样':active==='logic'?'播放波形':'播放穿过线圈';for(const output of document.querySelectorAll('[data-value]')){const key=output.dataset.value;output.textContent=state[active][key]+({rb:' Ω',load:' Ω',delay:' ms',time:' ms',voltage:' V'}[key]||'');}if(announce)document.getElementById('el-feedback').textContent=document.querySelector('#el-visual .lab-insight')?.textContent||'示意图已更新';}
 function stop(){clearTimeout(timer);timer=0;running=false;}
 function sampleInterface(){const s=state.interface,result=M.sample(s);s.last={...result,voltage:s.voltage,threshold:s.threshold};s.trace.unshift(result.valid?`${number(s.voltage)} V → ${result.code} → 输出${result.output?'高':'低'}`:'输入条件无效，逻辑输出置为未知');s.trace=s.trace.slice(0,5);}
 function sampleInduction(){const s=state.exploration,m=M.induction(s.turns,s.previous,s.position,.1,s.polarity);s.history.push({...m,previous:s.previous,position:s.position});s.history=s.history.slice(-20);s.previous=s.position;}
 function tick(){if(!running||!document.querySelector(`.extended-lab[data-lesson="${active}"]`)||document.hidden){stop();return;}const s=state[active];
  if(active==='logic'){s.time=Math.min(130,s.time+2);document.getElementById('el-time').value=s.time;if(s.time===130)stop();}
  if(active==='interface')sampleInterface();
  if(active==='exploration'){s.position=Math.min(3,s.position+.25);document.getElementById('el-position').value=s.position;sampleInduction();if(s.position===3)stop();}
  update();if(running)timer=setTimeout(tick,active==='interface'?600:active==='logic'?40:100);
 }
 function record(action,quiet=true){const id=active,l=ElectronicsLessons[id],s=state[id],stage=window.learningContext?.('lab',id)?.stage||'robotics-1';const matching=S.tasks.filter(t=>t.track==='robotics'&&t.stage===stage&&t.electronics_unit===id&&t.state!=='done');const result=document.getElementById('el-visual').innerText;return saveAutomaticJournal('lesson:'+id+':'+action,{title:l.name+'：'+l.question,track:'robotics',learning_route:'robotics',stage,kind:'experiment',evidence_type:id==='soldering'?'reading':'calculation',task_id:matching[0]?.id||'',question:l.question,procedure:l.scope+'\n\n当前条件：'+JSON.stringify(s,(k,v)=>['trace','history'].includes(k)?undefined:v),result:(id==='soldering'?'以下为网页练习预设检查，非实物测量：\n':'以下为网页教学模型结果，非实物测量：\n')+result,conclusion:'',prediction:'',links:[l.source],next_step:''},quiet);}
 function recordAnswer(l,value,feedback){return saveAutomaticJournal('lesson:'+active+':quiz',{title:l.name+'：自测作答',track:'robotics',learning_route:'robotics',stage:window.learningContext?.('lab',active)?.stage||'robotics-1',kind:'activity',evidence_type:'activity',question:l.challenge,result:'所选判断：'+l.options[Number(value)]+'\n反馈：'+feedback+'\n本次作答不代表已经掌握。',conclusion:'',links:[l.source]});}
 function bind(){if(!document.querySelector('.extended-lab')){stop();return;}update();}
 document.addEventListener('change',event=>{const key=event.target.dataset.el;if(!key)return;if(event.target.type==='range'){state[active][key]=Number(event.target.value);update();record('change');return;}const s=state[active];s[key]=event.target.type==='checkbox'?event.target.checked:event.target.tagName==='SELECT'&&['reference','polarity'].includes(key)?Number(event.target.value):event.target.value;
  if(active==='logic'){stop();if(key==='s'||key==='r')s.q=M.latch(s.s,s.r,s.q);if(key==='view'){document.getElementById('el-controls').innerHTML=controls(active);document.getElementById('el-answer-feedback').textContent='';}}
  if(active==='soldering')s.checks=[];
  if(active==='exploration'){s.previous=s.position;s.history=[];}
  update(true);record('change');
 });
 document.addEventListener('input',event=>{const key=event.target.dataset.el;if(!key||event.target.type!=='range')return;state[active][key]=Number(event.target.value);if(active!=='interface')stop();if(active==='exploration'&&key==='turns'){state.exploration.previous=state.exploration.position;state.exploration.history=[];}update(true);});
 document.addEventListener('click',event=>{const hole=event.target.closest('[data-el-hole]');if(hole){state.measurement.hole=hole.dataset.elHole;update();document.querySelector(`[data-el-hole="${hole.dataset.elHole}"]`)?.focus({preventScroll:true});record('hole');return;}
  const b=event.target.closest('[data-el-action]');if(!b)return;const a=b.dataset.elAction,s=state[active];
  if(a==='answer'){const v=document.getElementById('el-answer').value,l=ElectronicsLessons[active],feedback=v===''?'先选一个判断。':Number(v)===l.answer?'这个判断符合当前原理。'+l.explain:'再检查一下。'+l.explain;document.getElementById('el-answer-feedback').textContent=feedback;if(v!=='')recordAnswer(l,v,feedback);return;}
  if(a==='record'){stop();update();record('snapshot',false);return;}
  if(a.startsWith('check-')&&!s.checks.includes(a.slice(6)))s.checks.push(a.slice(6));
  if(a==='clear-checks')s.checks=[];
  if(a==='latch-reset'){s.s=false;s.r=false;s.q=0;document.getElementById('el-controls').innerHTML=controls(active);}
  if(a==='sample')sampleInterface();
  if(a==='induct-sample')sampleInduction();
  if(a==='restart'){stop();if(active==='logic'){s.time=0;document.getElementById('el-time').value=0;}else {s.position=-3;s.previous=-3;s.history=[];document.getElementById('el-position').value=-3;}}
  if(a==='play'){if(running)stop();else{if(active==='logic'&&s.time===130)s.time=0;if(active==='exploration'&&s.position===3){s.position=-3;s.previous=-3;s.history=[];}running=true;tick();if(active!=='interface'&&matchMedia('(prefers-reduced-motion: reduce)').matches)stop();}}
  update(true);record(a==='play'?(running?'play':'pause'):a);
 });
 document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();update();}});
 window.setElectronicsPreset=(id,values)=>{
  if(!Object.hasOwn(initial,id))throw Error('主题示例无效');
  const next=JSON.parse(JSON.stringify(initial[id]));
  for(const [key,value] of Object.entries(values)){
   if(['sample','seed_voltage','induct_sample'].includes(key))continue;
   if(!Object.hasOwn(next,key)||['last','trace','history'].includes(key))throw Error('示例字段无效');
   if(key==='checks'){if(!Array.isArray(value)||value.some(k=>!['continuity','isolation','mechanical'].includes(k)))throw Error('检查示例无效');next.checks=[...value];}
   else{if(typeof value!==typeof next[key]||(typeof value==='number'&&!Number.isFinite(value)))throw Error('示例类型无效');next[key]=value;}
  }
  const choices={mode:['V','R','I'],red:['P','A','M','G'],black:['P','A','M','G'],view:['gate','latch','bounce'],gate:['and','or','xor','nand'],scene:['normal','bridge','weak'],reference:[3.3,5],polarity:[-1,1],q:[0,1]};
  for(const [key,allowed] of Object.entries(choices))if(key in next&&!allowed.includes(next[key]))throw Error('示例选项无效');
  const ranges={rb:[100,10000],load:[50,1000],delay:[0,40],time:[0,130],voltage:[0,5],threshold:[0,1023],position:[-3,3],previous:[-3,3],turns:[50,500]};
  for(const [key,[low,high]] of Object.entries(ranges))if(key in next&&(next[key]<low||next[key]>high))throw Error('示例范围无效');
  if(id==='measurement')M.breadboardGroup(next.hole);
  if('seed_voltage' in values&&(id!=='interface'||!Number.isFinite(values.seed_voltage)||values.seed_voltage<0||values.seed_voltage>5))throw Error('采样示例无效');
  stop();state[id]=next;
  if(id==='interface'){if('seed_voltage' in values){const voltage=next.voltage;next.voltage=values.seed_voltage;sampleInterface();next.voltage=voltage;}else if(values.sample===true)sampleInterface();}
  if(id==='exploration'&&values.induct_sample===true)sampleInduction();
  render();
 };
 window.renderElectronicsLesson=renderElectronicsLesson;window.electronicsBind=bind;window.stopElectronicsLesson=stop;
}
