/* Optional stage zero. LED uses a fixed 2 V forward drop and a 20 mA exercise limit. */
const BasicCircuitModel={
 solve({voltage,resistance,closed,reversed,bypass}){
  if(![voltage,resistance].every(Number.isFinite)||voltage<0||voltage>5||resistance<=0)throw Error('起步电路参数无效');
  if(!closed)return {current:0,power:0,status:'open',over:false};
  if(bypass)return {current:null,power:null,status:'unlimited',over:null};
  if(reversed)return {current:0,power:0,status:'reversed',over:false};
  const current=Math.max(0,voltage-2)/resistance;
  return {current,power:current*current*resistance,status:current?'on':'below',over:current>.02};
 }
};
if(typeof module!=='undefined')module.exports=BasicCircuitModel;
if(typeof document!=='undefined'){
 let s={voltage:5,resistance:330,closed:false,reversed:false,bypass:false};
 function renderBasicCircuit(){return `<section class="panel circuit-lab basic-circuit" aria-labelledby="basic-title"><div class="lab-heading"><div><span class="study-kicker">零基础起步 · 不需要先买硬件</span><h2 id="basic-title">让第一盏灯亮起来，解释电流怎么走。</h2></div><span class="badge">理想 LED 教学模型</span></div><div class="lab-workspace"><div class="lab-controls"><label class="el-field">电源电压<select data-basic="voltage"><option value="3" ${s.voltage===3?'selected':''}>3 V</option><option value="5" ${s.voltage===5?'selected':''}>5 V</option></select></label><label class="lab-control" for="basic-resistance"><span>限流电阻 R<output id="basic-r-value">${s.resistance} Ω</output></span><input id="basic-resistance" data-basic="resistance" type="range" min="100" max="1000" step="10" value="${s.resistance}"></label>${[['closed','闭合开关'],['reversed','反转 LED（仅网页）'],['bypass','移除限流电阻（仅网页）']].map(([k,t])=>`<label class="lab-toggle"><input type="checkbox" data-basic="${k}" ${s[k]?'checked':''}>${t}</label>`).join('')}<p>先沿电源正端走一圈，找出回到负端的路径；再一次只改变一个条件。</p></div><div class="lab-visual" id="basic-visual"></div></div><div class="lab-bottom"><p>操作后的模型观察会自动保存到学习记录。图中为简化接线示意，圆形 LED 不代表标准电路符号。LED 正向压降固定为 2 V，20 mA 是本练习的假设上限；亮度仅作相对示意。真实元件有误差、非线性与反向耐压限制。反接、无电阻仅在网页中观察，不作为实物操作指引。</p><button type="button" class="btn primary" data-basic-record>保存当前观察</button></div></section>`;}
 function update(){const root=document.getElementById('basic-visual');if(!root)return;const m=BasicCircuitModel.solve(s),on=m.current>0;
  document.getElementById('basic-r-value').textContent=s.resistance+' Ω';document.getElementById('basic-resistance').disabled=s.bypass;
  const insight=m.status==='open'?'开关断开，回路不完整，电流为零。先找从电源正端返回负端的路径。':m.status==='unlimited'?'缺少限流元件，固定压降模型无法给出可信电流。不要把这个网页条件照搬到实物电路。':m.status==='reversed'?'本模型忽略反向漏电与击穿，反向电流按零处理；不能据此判断真实 LED 可以承受反接。':m.status==='below'?'电源不高于本模型假设的 2 V 压降，模型电流为零；真实 LED 特性更复杂。':`电阻承担 ${s.voltage}−2=${s.voltage-2} V，电流 I=(${s.voltage}−2)/${s.resistance}=${(m.current*1000).toFixed(2)} mA。${m.over?'超过本练习 20 mA 上限，不能照此作为实物选值。':'串联路径中电流相同，电阻不会把电流“用掉”。'}`;
  const path=`M70 60H120${s.closed?'H175':'L153 38M175 60'}H200M260 60H350V125M350 175V230H70V170M70 120V60`;
  root.innerHTML=`<svg class="el-svg basic-svg" viewBox="0 0 440 270" role="img" aria-label="电源、开关、电阻、LED 串联回路，${on?'模型发光':'模型未发光'}"><path d="${path}" class="el-wire ${on?'el-on':''}"/><circle cx="70" cy="145" r="25" class="el-part"/><text x="64" y="138">+</text><text x="64" y="161">−</text><text x="10" y="108">${s.voltage} V</text><text x="115" y="25">开关</text>${s.bypass?'<path d="M200 60H260" class="el-wire"/>':'<rect x="200" y="47" width="60" height="26" class="el-part"/>'}<text x="200" y="25">${s.bypass?'无电阻':'R'}</text><circle cx="350" cy="150" r="25" class="el-led ${on?'is-on':''}" fill-opacity="${on?Math.min(1,.3+m.current/.02*.7):1}"/><text x="295" y="117">${s.reversed?'K':'A'}</text><text x="295" y="197">${s.reversed?'A':'K'}</text><text x="385" y="156">LED</text><text x="95" y="260">正端 → 元件 → 返回负端</text>${on?'<path d="M95 60L87 55V65Z M350 105L345 97H355Z M110 230L118 225V235Z" class="basic-arrow"/>':''}</svg><dl class="el-metrics"><div><dt>回路电流</dt><dd>${m.current===null?'不作预测':(m.current*1000).toFixed(2)+' mA'}</dd></div><div><dt>电阻功率</dt><dd>${m.power===null?'不作预测':m.power.toFixed(3)+' W'}</dd></div></dl><p class="lab-insight" role="status">${insight}</p>`;
 }
 function preset(values){const defaults={voltage:5,resistance:330,closed:false,reversed:false,bypass:false};for(const k of Object.keys(defaults)){if(k in values&&typeof values[k]!==typeof defaults[k])throw Error('起步示例格式无效');}const next={...defaults,...Object.fromEntries(Object.entries(values).filter(([k])=>k in defaults))};BasicCircuitModel.solve(next);if(![3,5].includes(next.voltage)||next.resistance<100||next.resistance>1000)throw Error('起步示例范围无效');s=next;render();}
 document.addEventListener('input',e=>{if(e.target.dataset.basic!=='resistance')return;s.resistance=Number(e.target.value);update();});
 document.addEventListener('change',e=>{const k=e.target.dataset.basic;if(!k)return;s[k]=e.target.type==='checkbox'?e.target.checked:Number(e.target.value);update();recordBasic('change');});
 function recordBasic(action,quiet=true){const m=BasicCircuitModel.solve(s);return saveAutomaticJournal('basic:led:'+action,{title:'LED 模型：闭合回路与限流',track:'robotics',learning_route:'robotics',stage:window.learningContext?.('lab','basics')?.stage||'robotics-1',kind:'experiment',evidence_type:'calculation',question:'开关、LED 方向与电阻怎样影响电流？',procedure:'网页理想模型：LED 正向压降假设2 V，电流上限假设20 mA。条件：'+JSON.stringify(s),result:m.current===null?'当前模型无法预测电流，不能据此确定实物工作状态。':`模型电流 ${(m.current*1000).toFixed(2)} mA，电阻功率 ${m.power.toFixed(3)} W；不是实物测量。`,conclusion:'',links:['https://learn.sparkfun.com/tutorials/resistors/example-applications']},quiet);}
 document.addEventListener('click',e=>{if(e.target.closest('[data-basic-record]'))recordBasic('snapshot',false);});
 window.renderBasicCircuit=renderBasicCircuit;window.basicBind=update;window.setBasicCircuitPreset=preset;
}
